seeder: 
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/home.rb
    page_type: home
    disabled: false

  - file: ./parsers/image.rb
    page_type: image
    disabled: true

